#!/usr/bin/env bash
# Reads E2E secrets from GCP Secret Manager and writes them to apps/web/.env.e2e.local.
set -euo pipefail

: "${GCP_DEVOPS_PROJECT_ID:?GCP_DEVOPS_PROJECT_ID is required}"
: "${PROJECT:?PROJECT is required}"

OUTPUT="apps/web/.env.e2e.local"
SECRET_NAME="${PROJECT}-e2e-secrets"

RAW=$(gcloud secrets versions access latest \
  --secret="${SECRET_NAME}" \
  --project="${GCP_DEVOPS_PROJECT_ID}")

# Map legacy/short key names to canonical E2E_ prefixed names
normalise_key() {
  case "$1" in
    p1_password|P1_PASSWORD|e2e_p1_password) echo "E2E_P1_PASSWORD" ;;
    p2_password|P2_PASSWORD|e2e_p2_password) echo "E2E_P2_PASSWORD" ;;
    p1_user_id|P1_USER_ID|e2e_p1_user_id)   echo "E2E_P1_USER_ID"  ;;
    p2_user_id|P2_USER_ID|e2e_p2_user_id)   echo "E2E_P2_USER_ID"  ;;
    *) echo "${1^^}" ;;  # default: uppercase as-is
  esac
}

# Normalise to KEY=VALUE format, handling both KEY=value and key:value variants
{
  echo "# Generated by scripts/fetch-e2e-secrets.sh — DO NOT COMMIT"
  while IFS= read -r line; do
    # Skip blank lines and comments
    [[ -z "$line" || "$line" == \#* ]] && continue
    if [[ "$line" == *"="* ]]; then
      raw_key="${line%%=*}"
      val="${line#*=}"
    elif [[ "$line" == *":"* ]]; then
      raw_key="${line%%:*}"
      val="${line#*:}"
      val="${val#"${val%%[![:space:]]*}"}"  # strip leading whitespace
    else
      continue
    fi
    echo "$(normalise_key "$raw_key")=${val}"
  done <<< "${RAW}"
} > "${OUTPUT}"

echo "Secrets written to ${OUTPUT}"
