#!/usr/bin/env bash
# Reads E2E secrets from GCP Secret Manager and writes them to apps/web/.env.e2e.local.
set -euo pipefail

: "${GCP_DEVOPS_PROJECT_ID:?GCP_DEVOPS_PROJECT_ID is required}"
: "${PROJECT:?PROJECT is required}"

OUTPUT="apps/web/.env.e2e.local"
SECRET_NAME="${PROJECT}-e2e-secrets"

echo "# Generated by scripts/fetch-e2e-secrets.sh — DO NOT COMMIT" > "${OUTPUT}"
gcloud secrets versions access latest \
  --secret="${SECRET_NAME}" \
  --project="${GCP_DEVOPS_PROJECT_ID}" \
  >> "${OUTPUT}"

echo "Secrets written to ${OUTPUT}"
