#!/usr/bin/env bash
#MISE description="Run Terraform plan for shared infrastructure"
set -euo pipefail
mise run tf-init-shared
terraform -chdir=infra/shared plan \
  -var="project=${PROJECT}" \
  -var="gcp_project_id=${GCP_PROJECT_ID}" \
  -var="gcp_region=${GCP_REGION}" \
  -var="gcp_devops_project_id=${GCP_DEVOPS_PROJECT_ID}"
